{
  imports = [
    ./latex.nix
    ./neomutt
    ./newsboat
    ./scripts
    ./yazi
    ./zellij

    ./bat.nix
    ./bottom.nix
    ./dircolors.nix
    ./editorconfig.nix
    ./eza.nix
    ./fastfetch.nix
    ./fzf.nix
    ./git.nix
    ./gh.nix
    ./gpg.nix
    ./man.nix
    ./nix-direnv.nix
    ./nix-index.nix
    ./nix-init.nix
    ./ranger.nix
    ./ripgrep.nix
    ./ssh.nix
    ./tealdeer.nix
    ./transient-services.nix
    ./xdg.nix
    ./zoxide.nix
    ./pass.nix
  ];
}
