# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  apple-fonts = {
    pname = "apple-fonts";
    version = "a0a8998b8d4644dea5e0aa452822abeff206d8eb";
    src = fetchFromGitHub {
      owner = "fefelixa";
      repo = "macfonts";
      rev = "a0a8998b8d4644dea5e0aa452822abeff206d8eb";
      fetchSubmodules = true;
      sha256 = "sha256-dBJ90Bhjx9R9IjfKW+YDnif4rZ8B6WuNM+Vf7hV5qXk=";
    };
    date = "2021-02-12";
  };
}
