# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  stats = {
    pname = "stats";
    version = "stats-v1.1.1";
    src = fetchurl {
      url = "https://github.com/harbassan/spicetify-apps/releases/download/stats-v1.1.1/spicetify-stats.release.zip";
      sha256 = "sha256-vToCbsfHyLQt7pTSOJ4UUC9brcXJ5UeFkYmheiLgpiY=";
    };
  };
}
