{
  imports = [
    ./colorizer.nix
    ./comment-box.nix
    ./comment.nix
    ./copilot.nix
    ./flash.nix
    ./grapple.nix
    ./hardtime.nix
    ./harpoon.nix
    ./illuminate.nix
    ./markview.nix
    ./mini.nix
    ./nvim-autopairs.nix
    ./obsidian.nix
    ./oil.nix
    ./ufo.nix
    ./undotree.nix
    ./whichkey.nix
    ./yaml-companion.nix
  ];
}
