name: Delete Branch on PR Close

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    if: >
      github.event.pull_request.merged == false &&
      startsWith(github.event.pull_request.head.ref, 'update/') &&
      github.event.pull_request.head.ref != 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branches: ${{ github.event.pull_request.head.ref }}
          soft_fail: false